export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
  timestamp: string;
}

export interface PaginatedResponse<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  number: number;
  size: number;
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  ADMITTED = 'ADMITTED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED',
}

export enum EmployeeType {
  ACADEMIC = 'ACADEMIC',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  CONTRACTUAL = 'CONTRACTUAL',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  ON_LEAVE = 'ON_LEAVE',
  HOLIDAY = 'HOLIDAY',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentType {
  APPLICATION_FEE = 'APPLICATION_FEE',
  ADMISSION_FEE = 'ADMISSION_FEE',
  SEMESTER_FEE = 'SEMESTER_FEE',
  SALARY_DISBURSEMENT = 'SALARY_DISBURSEMENT',
}

export enum NotificationType {
  ADMISSION_STATUS = 'ADMISSION_STATUS',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  RESULT_PUBLISHED = 'RESULT_PUBLISHED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  PROMOTION_APPROVED = 'PROMOTION_APPROVED',
  PROMOTION_REJECTED = 'PROMOTION_REJECTED',
  PAYROLL_PROCESSED = 'PAYROLL_PROCESSED',
  GENERAL_NOTICE = 'GENERAL_NOTICE',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
}

export enum AppraisalRating {
  OUTSTANDING = 'OUTSTANDING',
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  SATISFACTORY = 'SATISFACTORY',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  UNSATISFACTORY = 'UNSATISFACTORY',
}

export enum PromotionType {
  PROMOTION = 'PROMOTION',
  DEMOTION = 'DEMOTION',
}

export enum SeparationType {
  RESIGNATION = 'RESIGNATION',
  RETIREMENT = 'RETIREMENT',
  TERMINATION = 'TERMINATION',
  END_OF_CONTRACT = 'END_OF_CONTRACT',
}

export enum JobApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEWED = 'INTERVIEWED',
  OFFERED = 'OFFERED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export type RoleName =
  | 'ADMIN'
  | 'REGISTRAR'
  | 'HR'
  | 'PAYROLL'
  | 'ADMISSION'
  | 'FACULTY'
  | 'STUDENT'
  | 'APPLICANT'
  | 'EMPLOYEE';
