export enum NotificationType {
  ADMISSION_STATUS = 'ADMISSION_STATUS',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  RESULT_PUBLISHED = 'RESULT_PUBLISHED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  PROMOTION_APPROVED = 'PROMOTION_APPROVED',
  PROMOTION_REJECTED = 'PROMOTION_REJECTED',
  PAYROLL_PROCESSED = 'PAYROLL_PROCESSED',
  GENERAL_NOTICE = 'GENERAL_NOTICE',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
}
