package com.smartuniversity.common.enums;

public enum NotificationType {
    ADMISSION_STATUS,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    RESULT_PUBLISHED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    PROMOTION_APPROVED,
    PROMOTION_REJECTED,
    PAYROLL_PROCESSED,
    GENERAL_NOTICE,
    DOCUMENT_VERIFICATION,
    INTERVIEW_SCHEDULED
}
