package com.smartuniversity.common.enums;

public enum Permission {
    USER_READ, USER_WRITE, USER_DELETE,
    ROLE_READ, ROLE_WRITE, ROLE_DELETE,
    ADMISSION_READ, ADMISSION_WRITE, ADMISSION_APPROVE,
    ACADEMIC_READ, ACADEMIC_WRITE,
    STUDENT_READ, STUDENT_WRITE,
    HRM_READ, HRM_WRITE, HRM_APPROVE,
    PAYROLL_READ, PAYROLL_WRITE, PAYROLL_APPROVE,
    PAYMENT_READ, PAYMENT_WRITE,
    NOTIFICATION_READ, NOTIFICATION_WRITE,
    AUDIT_READ
}
